#ifndef  _H_IRIS2DCOMPILERCONFIGURE_
#define  _H_IRIS2DCOMPILERCONFIGURE_

#define IR_API_VERSION 0 // 0 = OpenGL 1 = DirectX

#define IR_USE_DEPRECATED_API 0
#define IR_USE_SMART_POINTER 1
#define IR_EXPORT_C_API 0

#endif // ! _H_IRIS2DCOMPILERCONFIGURE_